application: hd-dashboard
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /login
  script: login.application
- url: /_km/.*
  script: keymaster.app
  login: admin
- url: .*
  script: main.application

